### ISSUE TITLE
#67 - [Iniciação Ciêntifica] Um Direito à Explicação com Carla Vieira

### ISSUE THREAD

**Issue by reginaldojunior** [QuebraDev/esteira-de-episodios#3]
https://docs.google.com/document/d/1BdpCgVckEUx4cuc7Aqe3liBywcj1-K3oZz0MU9mRHC8/edit?usp=sharing

**Comment by gustavocstl** [comment]
Episódio publicado:
https://quebra.dev/um-direito-a-explicacao-com-carla-vieira/
